name: Test
on:
  push:
    branches:
      - master
    paths:
      - "customers/web/**"
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
        name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test:web
